### PR TITLE
Create ldfr

### PR DESCRIPTION
**Pull request by mnazmulislam**
I am submitting code for implementing the LDFR function for the methods described in Islam, Md Nazmul, Staicu, A.M., and Heugten, Eric-Van. Longitudinal Dynamic Functional Regression. Journal of Royal Statistical Society, Series C (under revision).

### CODE REVIEW

**Comment by fabian-s** [comment]
Thank you for your contribution, sorry for the delayed review. You code needs a little addditional work before we can merge it -- you need to make sure that the submitted code is a standards-compliant R package that respects all the implicit and explicit conventions for CRAN R packages in general and `refund`, specifically.

## Issues:

**basic structure:**

-  your function `LDFR`  needs to be in a file in subfolder `R` named `ldfr.R` (we try to keep function  names lower case, so please change this as well)
- the modified package should pass `R CMD check --as-cran` without any NOTES, WARNINGS or ERRORS  (at least: without any NOTES, WARNINGS or ERRORS triggered by your changes, i.e., I get: 
``` 
* checking top-level files ... NOTE
Non-standard file/directory found at top level:
  ‘LDFR’
``` 
- it would be **much** preferable to have your function return an S3 object for which suitable `fitted`, `predict`, `plot`, `summary` and `residuals`-methods are defined, like `pffr` and `pfr` do. It's perfectly fine to write lightweight wrappers around the corresponding methods for `bam`-objects for this. Having one huge function with ~1000 lines that returns a bare `list` do all the fitting, plotting etc  is not best practice -- see also the guidelines at https://developer.r-project.org/model-fitting-functions.html. 
- please take care to write [*pure functions*](https://adv-r.hadley.nz/functions.html#return-values) that do not have side effects like changing the users' graphics device settings. If you modify user-side settings e.g. via `par()`, please also include corresponding `on.exit` statements to undo such changes after the function terminates.
- please add suitable `testthat`-tests for the basic functionality of your code
- please take care to [avoid the usual "Undefined global functions or variables:"-NOTEs that always come up with package code that uses `ggplot2`](https://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when)

**dependencies**

- your code declares dependencies via `@import` -- please make sure to restrict those to the ones that are really necessary by using `@importFrom` like other functions in `refund`
- `#' @import refund` breaks R CMD check and is unnecessary in `refund`'s own functions
- you're missing some dependencies, like `grDevices::colorRampPalette`

**documentation:**

- when I copy your file to the R subfolder and compile the help, the resulting help page does not render correctly (you have 2 spaces in your `roxygen` comments):
image

- please don't use lines with >100 characters in your example
- please document the functions you define in your examples (e.g. `onesubj`)
-  consider putting the non-essential parts of your very long example into supporting material like a vignette, a Github gist, RPubs post or on your website.

**Comment by mnazmulislam** [comment]
Thanks so much for your valuable comments. I have made changes and asked for a pull request in the devel branch of refund. I added the function in R folder with function ldfr.R. Could you please take a look at it and let me know?

**Comment by mnazmulislam** [comment]
Just to add to it, I have both added the function here and pulled a new request. In the new request, I have added the ldfr.R function in the subfolder named R.

**Comment by fabian-s** [comment]
Thanks, but please commit the changes you made to fix the issues pointed out above directly to https://github.com/mnazmulislam/refund/tree/patch-1 so they show up in this pull request. That way we can track the changes automatically and don't have to go through the code line by line. Uploading files via GitHub is not the right way to do a (non-trivial) pull request, I'm closing the other PR. Sorry for the inconvenience...

**Comment by mnazmulislam** [comment]
Thanks for your response. I have found a label named "LDFR" and "Update LDFR" in https://github.com/mnazmulislam/refund/tree/patch-1.  As I click "Update LDFR", I see the changes; for instance, the lines deleted and added are colored differently. Is this what you are referring to? I am so sorry; I am not very familiar with the process. I sincerely apologize for any confusion. Would you please clarify if I understand it correctly? Thanks so much in advance.

**Comment by fabian-s** [comment]
As it says immediately below this comment: 
"Add more commits by pushing to the patch-1 branch on mnazmulislam/refund."

So, you need to do something like (no guarantees, I don't know your setup)

Within your local cloned repository on your own machine do  
`git checkout patch-1`  in order to switch to the branch for this pull-request  
`git merge <name of the branch where you put the changes that fix *ALL* of the issues pointed out above>`  to incorporate the changes you made into the branch for this PR
`git rm LDFR` to delete the now superfluous file that was replaced by `R/LDFR.R`
`git commit -m  "rm LDFR at wrong location"`  
`git push` in order to make your changes available here

I don't mean to be rude, but please understand that it's not our job to teach you how to use Git and GitHub and we won't spend more time writing out explanations for that.    
There are many wonderful Git tutorials available for free online, please use them if you run into problems or find someone knowledgeable in your own institution to help you out.

**Comment by jeff-goldsmith** [comment]
Checking on this -- it looks like the requested changes were made in a separate repository, but never included in the patch-1 branch of mnazmulislam/refund. Is that accurate? If so, can the changes addresses each of @fabian-s's comments be included in this pull request?

**Comment by fabian-s** [comment]
@mnazmulislam : Closing this since you never replied nor took further action on these issues. Please do let us know if you are still working on this or need more assistance on getting this code into `refund`.

**Pull request closed without merging**
